
language: node_js
node_js:
  - "6"
  - "6.1"
  - "5.11"

before_script:
  - npm install -g gulp bower

script:
  - gulp test
  # - gulp test:css

cache:
  directories:
    - node_modules

addons:
  srcclr: true