language: node_js
node_js:
- '6'
before_script:
- npm install -g gulp bower
script:
- gulp test
- gulp test:css
cache:
  directories:
  - node_modules
addons:
  srcclr: true
deploy:
  provider: heroku
  api_key:
    secure: WikrLDJVbkM9g/F0SFEGO227OGaqWyYkVAY2/rddmbWy7487cyKXEloX72579Z4UMf4s7ANOSCcVhd4KuM9a50MPQhk4F1uMoXanDqjWLXypw9M6xGXz7/MeJESSblgeYEsaoPtHuIXP9AmviDpL27kuoTA06tu16eXtyjUo7zZNTcbXDgtNSnYSSvoeuY9sHSHWv4G8cbav/CBlMWehdWHylMdWXHaN+GKH0hGEZQsPWXP+ppA3XqJ3O/afLZpfnfBAIYqYAueJcFWpf+vFLn5I3XHohJw6dfLwzc4MZg+4IAL6jY/Cfxyp3p8C5PpyvrrvfkTjBwmJY3hsN+c70D0zxF+UX4k9Ho/kJL1yYdxcepoPulcpSRLY9knNTk+PibY4VZXv2A5pGgrVxofBQx9yAOgvHtGV8v7uzhMFvrQPQ3akn5qoxDcgskcI/bUTdOaZUY8pxflLoN/jt58fgYMQL4fMp0LkK2KA+Hq6If0OoIbRyntC03RyAIsl7A3jzMaXfP6lFkRH1/Ii+ptXMaQsTn3AmDpSCwiq0DKvnRbZD7D11bOXwaEGLxMz00F1GDqIFvZHKvK5KdNGwlDO3Ts7f7XaHVaB/SPeMC4G4+W9sBdVm3y+VsWT6PI62V+DQSukv8GpJcIG7dExmW5MwmPn3BwAIWs8pg2IIoZgfHk=
  app: warm-shore-75862
  on:
    repo: patengelbert/sei_ci_webapp
