language: node_js
node_js:
- '7'
before_script:
- npm install -g gulp bower
script:
- gulp test
- gulp test:css
cache:
  directories:
  - node_modules
addons:
  srcclr: true
deploy:
  provider: heroku
  api_key:
    secure: hfSXWsmWB8kanCla/zhM11wJ2qJ5tPHfY3to0lu3D7xNCocz6LXQO4KUoH2Dl2eXyVUDqacU3hyvABI4ApN0f6Z6HiZDsBjs/yUgju8hvkL6Z1Ra3hOm/W3ZOBx8ImaB0CXUApYH16tPZpRUuAxF7b7y0K8EQu6U8zIJ/z2ixh5+q7MUJgjatt2k1ZMhEZe7wAUxfQDYPfmqPd8QvGzY7w3C0cAXaroX6xtCleld9cl4607O1oyG8ZKh64asFOFrYzcrPC5i6y8BOhJtjoCbpcoE8Smc5d0DrsaMoY87PpA3v9u6/XRqj3NKmZRpRmd3DJTeVNgZqpXyxN58cNQe9cmNVgKvAV9B5f4gbf/WVeIR+i/vyFM4H/eQ9TOfGFyxjSfM74anWYRGo9IlGi4WzXLwSDy0hezS7MQssG0XBtal9fjRDNyEJo/Aj0Tt8uUxdE2Vu7ywoUZjmitlOVHP4GxBc+kjDhK0Lox76Ov4/qKjELSBRpTNUJiTcD16nQ8x68byXc+CAowCcKcsDiCkKqqCKeozylHIAosRmUbEOgu5VWhfmlA+SRhGrp9rsICs4rmq5iHGHThNa4tfJAVZsS607gp8yergUaMUr8M0whgN1+0g0VF+b0LuuUxbJl+YwrIDNam+nVMmKZOKRoQhm7AuRmhJGJxNlYC9C+OXCWs=
  app:
    master: sei-ci-webapp-staging
    production: sei-ci-webapp
  on:
    repo: patengelbert/sei_ci_webapp
